/* 
 * Signing Today Web
 *
 * *Signing Today* is the perfect Digital Signature Gateway. Whenever in Your workflow You need to add one or more Digital Signatures to Your document, *Signing Today* is the right choice. You prepare Your documents, *Signing Today* takes care of all the rest: send invitations (`signature tickets`) to signers, collects their signatures, send You back the signed document. Integrating *Signing Today* in Your existing applications is very easy. Just follow these API specifications and get inspired by the many examples presented hereafter. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using SigningToday.Client;
using SigningToday.Api;
using SigningToday.Model;

namespace SigningToday.Test
{
    /// <summary>
    ///  Class for testing Bit4idPathgroupResourcesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class Bit4idPathgroupResourcesApiTests
    {
        private Bit4idPathgroupResourcesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new Bit4idPathgroupResourcesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Bit4idPathgroupResourcesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' Bit4idPathgroupResourcesApi
            //Assert.IsInstanceOf(typeof(Bit4idPathgroupResourcesApi), instance);
        }

        
        /// <summary>
        /// Test DSTIdResourcesGet
        /// </summary>
        [Test]
        public void DSTIdResourcesGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //var response = instance.DSTIdResourcesGet(id);
            //Assert.IsInstanceOf(typeof(System.IO.Stream), response, "response is System.IO.Stream");
        }
        
        /// <summary>
        /// Test DSTIdResourcesPatch
        /// </summary>
        [Test]
        public void DSTIdResourcesPatchTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //System.IO.Stream file = null;
            //string filename = null;
            //string resourceType = null;
            //string title = null;
            //var response = instance.DSTIdResourcesPatch(id, file, filename, resourceType, title);
            //Assert.IsInstanceOf(typeof(DigitalSignatureTransaction), response, "response is DigitalSignatureTransaction");
        }
        
        /// <summary>
        /// Test DSTResourceIdDelete
        /// </summary>
        [Test]
        public void DSTResourceIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //var response = instance.DSTResourceIdDelete(id);
            //Assert.IsInstanceOf(typeof(DigitalSignatureTransaction), response, "response is DigitalSignatureTransaction");
        }
        
        /// <summary>
        /// Test ResourceIdGet
        /// </summary>
        [Test]
        public void ResourceIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //var response = instance.ResourceIdGet(id);
            //Assert.IsInstanceOf(typeof(System.IO.Stream), response, "response is System.IO.Stream");
        }
        
        /// <summary>
        /// Test ResourceIdPut
        /// </summary>
        [Test]
        public void ResourceIdPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //LFResource lFResource = null;
            //instance.ResourceIdPut(id, lFResource);
            
        }
        
        /// <summary>
        /// Test UserIdIdentityIdentityIdAppearanceDelete
        /// </summary>
        [Test]
        public void UserIdIdentityIdentityIdAppearanceDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //Guid identityId = null;
            //instance.UserIdIdentityIdentityIdAppearanceDelete(id, identityId);
            
        }
        
        /// <summary>
        /// Test UserIdIdentityIdentityIdAppearanceGet
        /// </summary>
        [Test]
        public void UserIdIdentityIdentityIdAppearanceGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //Guid identityId = null;
            //var response = instance.UserIdIdentityIdentityIdAppearanceGet(id, identityId);
            //Assert.IsInstanceOf(typeof(System.IO.Stream), response, "response is System.IO.Stream");
        }
        
        /// <summary>
        /// Test UserIdIdentityIdentityIdAppearancePost
        /// </summary>
        [Test]
        public void UserIdIdentityIdentityIdAppearancePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //Guid identityId = null;
            //System.IO.Stream file = null;
            //string filename = null;
            //string resourceType = null;
            //string title = null;
            //var response = instance.UserIdIdentityIdentityIdAppearancePost(id, identityId, file, filename, resourceType, title);
            //Assert.IsInstanceOf(typeof(LFResource), response, "response is LFResource");
        }
        
    }

}
