/* 
 * Signing Today Web
 *
 * *Signing Today* is the perfect Digital Signature Gateway. Whenever in Your workflow You need to add one or more Digital Signatures to Your document, *Signing Today* is the right choice. You prepare Your documents, *Signing Today* takes care of all the rest: send invitations (`signature tickets`) to signers, collects their signatures, send You back the signed document. Integrating *Signing Today* in Your existing applications is very easy. Just follow these API specifications and get inspired by the many examples presented hereafter. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SigningToday.Api;
using SigningToday.Model;
using SigningToday.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SigningToday.Test
{
    /// <summary>
    ///  Class for testing AuditRecord
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AuditRecordTests
    {
        // TODO uncomment below to declare an instance variable for AuditRecord
        //private AuditRecord instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AuditRecord
            //instance = new AuditRecord();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AuditRecord
        /// </summary>
        [Test]
        public void AuditRecordInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" AuditRecord
            //Assert.IsInstanceOf(typeof(AuditRecord), instance);
        }


        /// <summary>
        /// Test the property 'InstanceId'
        /// </summary>
        [Test]
        public void InstanceIdTest()
        {
            // TODO unit test for the property 'InstanceId'
        }
        /// <summary>
        /// Test the property 'At'
        /// </summary>
        [Test]
        public void AtTest()
        {
            // TODO unit test for the property 'At'
        }
        /// <summary>
        /// Test the property 'Event'
        /// </summary>
        [Test]
        public void EventTest()
        {
            // TODO unit test for the property 'Event'
        }
        /// <summary>
        /// Test the property 'Signer'
        /// </summary>
        [Test]
        public void SignerTest()
        {
            // TODO unit test for the property 'Signer'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'DstId'
        /// </summary>
        [Test]
        public void DstIdTest()
        {
            // TODO unit test for the property 'DstId'
        }
        /// <summary>
        /// Test the property 'DocumentId'
        /// </summary>
        [Test]
        public void DocumentIdTest()
        {
            // TODO unit test for the property 'DocumentId'
        }
        /// <summary>
        /// Test the property 'FillableFormId'
        /// </summary>
        [Test]
        public void FillableFormIdTest()
        {
            // TODO unit test for the property 'FillableFormId'
        }
        /// <summary>
        /// Test the property 'SignatureRequestId'
        /// </summary>
        [Test]
        public void SignatureRequestIdTest()
        {
            // TODO unit test for the property 'SignatureRequestId'
        }
        /// <summary>
        /// Test the property 'NoteId'
        /// </summary>
        [Test]
        public void NoteIdTest()
        {
            // TODO unit test for the property 'NoteId'
        }

    }

}
