/* 
 * Signing Today Web
 *
 * *Signing Today* is the perfect Digital Signature Gateway. Whenever in Your workflow You need to add one or more Digital Signatures to Your document, *Signing Today* is the right choice. You prepare Your documents, *Signing Today* takes care of all the rest: send invitations (`signature tickets`) to signers, collects their signatures, send You back the signed document. Integrating *Signing Today* in Your existing applications is very easy. Just follow these API specifications and get inspired by the many examples presented hereafter. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SigningToday.Api;
using SigningToday.Model;
using SigningToday.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SigningToday.Test
{
    /// <summary>
    ///  Class for testing DeviceAuthorizationResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeviceAuthorizationResponseTests
    {
        // TODO uncomment below to declare an instance variable for DeviceAuthorizationResponse
        //private DeviceAuthorizationResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DeviceAuthorizationResponse
            //instance = new DeviceAuthorizationResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DeviceAuthorizationResponse
        /// </summary>
        [Test]
        public void DeviceAuthorizationResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DeviceAuthorizationResponse
            //Assert.IsInstanceOf(typeof(DeviceAuthorizationResponse), instance);
        }


        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Test]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'BaseURL'
        /// </summary>
        [Test]
        public void BaseURLTest()
        {
            // TODO unit test for the property 'BaseURL'
        }
        /// <summary>
        /// Test the property 'Challenge'
        /// </summary>
        [Test]
        public void ChallengeTest()
        {
            // TODO unit test for the property 'Challenge'
        }

    }

}
