/* 
 * Signing Today Web
 *
 * *Signing Today* is the perfect Digital Signature Gateway. Whenever in Your workflow You need to add one or more Digital Signatures to Your document, *Signing Today* is the right choice. You prepare Your documents, *Signing Today* takes care of all the rest: send invitations (`signature tickets`) to signers, collects their signatures, send You back the signed document. Integrating *Signing Today* in Your existing applications is very easy. Just follow these API specifications and get inspired by the many examples presented hereafter. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SigningToday.Api;
using SigningToday.Model;
using SigningToday.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SigningToday.Test
{
    /// <summary>
    ///  Class for testing DigitalSignatureTransaction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DigitalSignatureTransactionTests
    {
        // TODO uncomment below to declare an instance variable for DigitalSignatureTransaction
        //private DigitalSignatureTransaction instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DigitalSignatureTransaction
            //instance = new DigitalSignatureTransaction();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DigitalSignatureTransaction
        /// </summary>
        [Test]
        public void DigitalSignatureTransactionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DigitalSignatureTransaction
            //Assert.IsInstanceOf(typeof(DigitalSignatureTransaction), instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Domain'
        /// </summary>
        [Test]
        public void DomainTest()
        {
            // TODO unit test for the property 'Domain'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Replaces'
        /// </summary>
        [Test]
        public void ReplacesTest()
        {
            // TODO unit test for the property 'Replaces'
        }
        /// <summary>
        /// Test the property 'ReplacedBy'
        /// </summary>
        [Test]
        public void ReplacedByTest()
        {
            // TODO unit test for the property 'ReplacedBy'
        }
        /// <summary>
        /// Test the property 'CreatedByUser'
        /// </summary>
        [Test]
        public void CreatedByUserTest()
        {
            // TODO unit test for the property 'CreatedByUser'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'Documents'
        /// </summary>
        [Test]
        public void DocumentsTest()
        {
            // TODO unit test for the property 'Documents'
        }
        /// <summary>
        /// Test the property 'PublishedAt'
        /// </summary>
        [Test]
        public void PublishedAtTest()
        {
            // TODO unit test for the property 'PublishedAt'
        }
        /// <summary>
        /// Test the property 'ExpiresAt'
        /// </summary>
        [Test]
        public void ExpiresAtTest()
        {
            // TODO unit test for the property 'ExpiresAt'
        }
        /// <summary>
        /// Test the property 'Resources'
        /// </summary>
        [Test]
        public void ResourcesTest()
        {
            // TODO unit test for the property 'Resources'
        }
        /// <summary>
        /// Test the property 'Signatures'
        /// </summary>
        [Test]
        public void SignaturesTest()
        {
            // TODO unit test for the property 'Signatures'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'ErrorMessage'
        /// </summary>
        [Test]
        public void ErrorMessageTest()
        {
            // TODO unit test for the property 'ErrorMessage'
        }
        /// <summary>
        /// Test the property 'DeletedAt'
        /// </summary>
        [Test]
        public void DeletedAtTest()
        {
            // TODO unit test for the property 'DeletedAt'
        }
        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Test]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }
        /// <summary>
        /// Test the property 'Template'
        /// </summary>
        [Test]
        public void TemplateTest()
        {
            // TODO unit test for the property 'Template'
        }
        /// <summary>
        /// Test the property 'PublicTemplate'
        /// </summary>
        [Test]
        public void PublicTemplateTest()
        {
            // TODO unit test for the property 'PublicTemplate'
        }
        /// <summary>
        /// Test the property 'ExtraData'
        /// </summary>
        [Test]
        public void ExtraDataTest()
        {
            // TODO unit test for the property 'ExtraData'
        }
        /// <summary>
        /// Test the property 'VisibleTo'
        /// </summary>
        [Test]
        public void VisibleToTest()
        {
            // TODO unit test for the property 'VisibleTo'
        }
        /// <summary>
        /// Test the property 'CcGroups'
        /// </summary>
        [Test]
        public void CcGroupsTest()
        {
            // TODO unit test for the property 'CcGroups'
        }
        /// <summary>
        /// Test the property 'CcUsers'
        /// </summary>
        [Test]
        public void CcUsersTest()
        {
            // TODO unit test for the property 'CcUsers'
        }
        /// <summary>
        /// Test the property 'Urgent'
        /// </summary>
        [Test]
        public void UrgentTest()
        {
            // TODO unit test for the property 'Urgent'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Test]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

    }

}
