/* 
 * Signing Today Web
 *
 * *Signing Today* is the perfect Digital Signature Gateway. Whenever in Your workflow You need to add one or more Digital Signatures to Your document, *Signing Today* is the right choice. You prepare Your documents, *Signing Today* takes care of all the rest: send invitations (`signature tickets`) to signers, collects their signatures, send You back the signed document. Integrating *Signing Today* in Your existing applications is very easy. Just follow these API specifications and get inspired by the many examples presented hereafter. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SigningToday.Api;
using SigningToday.Model;
using SigningToday.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SigningToday.Test
{
    /// <summary>
    ///  Class for testing Document
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DocumentTests
    {
        // TODO uncomment below to declare an instance variable for Document
        //private Document instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Document
            //instance = new Document();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Document
        /// </summary>
        [Test]
        public void DocumentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Document
            //Assert.IsInstanceOf(typeof(Document), instance);
        }


        /// <summary>
        /// Test the property 'InstanceId'
        /// </summary>
        [Test]
        public void InstanceIdTest()
        {
            // TODO unit test for the property 'InstanceId'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'PlainDocumentUuid'
        /// </summary>
        [Test]
        public void PlainDocumentUuidTest()
        {
            // TODO unit test for the property 'PlainDocumentUuid'
        }
        /// <summary>
        /// Test the property 'FilledDocumentUuid'
        /// </summary>
        [Test]
        public void FilledDocumentUuidTest()
        {
            // TODO unit test for the property 'FilledDocumentUuid'
        }
        /// <summary>
        /// Test the property 'SignedDocumentUuid'
        /// </summary>
        [Test]
        public void SignedDocumentUuidTest()
        {
            // TODO unit test for the property 'SignedDocumentUuid'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Forms'
        /// </summary>
        [Test]
        public void FormsTest()
        {
            // TODO unit test for the property 'Forms'
        }
        /// <summary>
        /// Test the property 'SignatureRequests'
        /// </summary>
        [Test]
        public void SignatureRequestsTest()
        {
            // TODO unit test for the property 'SignatureRequests'
        }
        /// <summary>
        /// Test the property 'SignerGroups'
        /// </summary>
        [Test]
        public void SignerGroupsTest()
        {
            // TODO unit test for the property 'SignerGroups'
        }

    }

}
