/* 
 * Signing Today Web
 *
 * *Signing Today* is the perfect Digital Signature Gateway. Whenever in Your workflow You need to add one or more Digital Signatures to Your document, *Signing Today* is the right choice. You prepare Your documents, *Signing Today* takes care of all the rest: send invitations (`signature tickets`) to signers, collects their signatures, send You back the signed document. Integrating *Signing Today* in Your existing applications is very easy. Just follow these API specifications and get inspired by the many examples presented hereafter. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SigningToday.Api;
using SigningToday.Model;
using SigningToday.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SigningToday.Test
{
    /// <summary>
    ///  Class for testing IdentityProviderDataTokenInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IdentityProviderDataTokenInfoTests
    {
        // TODO uncomment below to declare an instance variable for IdentityProviderDataTokenInfo
        //private IdentityProviderDataTokenInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of IdentityProviderDataTokenInfo
            //instance = new IdentityProviderDataTokenInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of IdentityProviderDataTokenInfo
        /// </summary>
        [Test]
        public void IdentityProviderDataTokenInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" IdentityProviderDataTokenInfo
            //Assert.IsInstanceOf(typeof(IdentityProviderDataTokenInfo), instance);
        }


        /// <summary>
        /// Test the property 'UlMinPinLen'
        /// </summary>
        [Test]
        public void UlMinPinLenTest()
        {
            // TODO unit test for the property 'UlMinPinLen'
        }
        /// <summary>
        /// Test the property 'ManufacturerID'
        /// </summary>
        [Test]
        public void ManufacturerIDTest()
        {
            // TODO unit test for the property 'ManufacturerID'
        }
        /// <summary>
        /// Test the property 'UlFreePublicMemory'
        /// </summary>
        [Test]
        public void UlFreePublicMemoryTest()
        {
            // TODO unit test for the property 'UlFreePublicMemory'
        }
        /// <summary>
        /// Test the property 'SerialNumber'
        /// </summary>
        [Test]
        public void SerialNumberTest()
        {
            // TODO unit test for the property 'SerialNumber'
        }
        /// <summary>
        /// Test the property 'UlTotalPublicMemory'
        /// </summary>
        [Test]
        public void UlTotalPublicMemoryTest()
        {
            // TODO unit test for the property 'UlTotalPublicMemory'
        }
        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Test]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }
        /// <summary>
        /// Test the property 'Flags'
        /// </summary>
        [Test]
        public void FlagsTest()
        {
            // TODO unit test for the property 'Flags'
        }
        /// <summary>
        /// Test the property 'UlTotalPrivateMemory'
        /// </summary>
        [Test]
        public void UlTotalPrivateMemoryTest()
        {
            // TODO unit test for the property 'UlTotalPrivateMemory'
        }
        /// <summary>
        /// Test the property 'Model'
        /// </summary>
        [Test]
        public void ModelTest()
        {
            // TODO unit test for the property 'Model'
        }
        /// <summary>
        /// Test the property 'UlFreePrivateMemory'
        /// </summary>
        [Test]
        public void UlFreePrivateMemoryTest()
        {
            // TODO unit test for the property 'UlFreePrivateMemory'
        }
        /// <summary>
        /// Test the property 'UlMaxPinLen'
        /// </summary>
        [Test]
        public void UlMaxPinLenTest()
        {
            // TODO unit test for the property 'UlMaxPinLen'
        }

    }

}
