/* 
 * Signing Today Web
 *
 * *Signing Today* is the perfect Digital Signature Gateway. Whenever in Your workflow You need to add one or more Digital Signatures to Your document, *Signing Today* is the right choice. You prepare Your documents, *Signing Today* takes care of all the rest: send invitations (`signature tickets`) to signers, collects their signatures, send You back the signed document. Integrating *Signing Today* in Your existing applications is very easy. Just follow these API specifications and get inspired by the many examples presented hereafter. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SigningToday.Api;
using SigningToday.Model;
using SigningToday.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SigningToday.Test
{
    /// <summary>
    ///  Class for testing LFResource
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LFResourceTests
    {
        // TODO uncomment below to declare an instance variable for LFResource
        //private LFResource instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LFResource
            //instance = new LFResource();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LFResource
        /// </summary>
        [Test]
        public void LFResourceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" LFResource
            //Assert.IsInstanceOf(typeof(LFResource), instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Domain'
        /// </summary>
        [Test]
        public void DomainTest()
        {
            // TODO unit test for the property 'Domain'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'DstUuid'
        /// </summary>
        [Test]
        public void DstUuidTest()
        {
            // TODO unit test for the property 'DstUuid'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Filename'
        /// </summary>
        [Test]
        public void FilenameTest()
        {
            // TODO unit test for the property 'Filename'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Test]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'Mimetype'
        /// </summary>
        [Test]
        public void MimetypeTest()
        {
            // TODO unit test for the property 'Mimetype'
        }
        /// <summary>
        /// Test the property 'Pages'
        /// </summary>
        [Test]
        public void PagesTest()
        {
            // TODO unit test for the property 'Pages'
        }
        /// <summary>
        /// Test the property 'ExtraData'
        /// </summary>
        [Test]
        public void ExtraDataTest()
        {
            // TODO unit test for the property 'ExtraData'
        }

    }

}
