/* 
 * Signing Today Web
 *
 * *Signing Today* is the perfect Digital Signature Gateway. Whenever in Your workflow You need to add one or more Digital Signatures to Your document, *Signing Today* is the right choice. You prepare Your documents, *Signing Today* takes care of all the rest: send invitations (`signature tickets`) to signers, collects their signatures, send You back the signed document. Integrating *Signing Today* in Your existing applications is very easy. Just follow these API specifications and get inspired by the many examples presented hereafter. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using SigningToday.Client;
using SigningToday.Model;

namespace SigningToday.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IBit4idPathgroupRobotsApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Clear a Robot authentication lifetime token
        /// </summary>
        /// <remarks>
        /// This API allows to clear the Robot authentication lifetime token.
        /// </remarks>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username">The _username_ associated to the account (optional)</param>
        /// <param name="domain">The _domain_ associated to the account (optional)</param>
        /// <returns></returns>
        void RobotAuthenticationDelete (string username = default(string), string domain = default(string));

        /// <summary>
        /// Clear a Robot authentication lifetime token
        /// </summary>
        /// <remarks>
        /// This API allows to clear the Robot authentication lifetime token.
        /// </remarks>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username">The _username_ associated to the account (optional)</param>
        /// <param name="domain">The _domain_ associated to the account (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> RobotAuthenticationDeleteWithHttpInfo (string username = default(string), string domain = default(string));
        /// <summary>
        /// Retrieve the Robot authentication lifetime token
        /// </summary>
        /// <remarks>
        /// This API allows to generate or retrieves the Robot authentication lifetime token for the specified robot account, or the current logged in account. 
        /// </remarks>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username">The _username_ associated to the account (optional)</param>
        /// <param name="domain">The _domain_ associated to the account (optional)</param>
        /// <returns>RobotAuthenticationToken</returns>
        RobotAuthenticationToken RobotAuthenticationGet (string username = default(string), string domain = default(string));

        /// <summary>
        /// Retrieve the Robot authentication lifetime token
        /// </summary>
        /// <remarks>
        /// This API allows to generate or retrieves the Robot authentication lifetime token for the specified robot account, or the current logged in account. 
        /// </remarks>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username">The _username_ associated to the account (optional)</param>
        /// <param name="domain">The _domain_ associated to the account (optional)</param>
        /// <returns>ApiResponse of RobotAuthenticationToken</returns>
        ApiResponse<RobotAuthenticationToken> RobotAuthenticationGetWithHttpInfo (string username = default(string), string domain = default(string));
        /// <summary>
        /// Retrieve the Robot configuration
        /// </summary>
        /// <remarks>
        /// This API allows to retrieve the Robot configuration. 
        /// </remarks>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username">The _username_ associated to the account (optional)</param>
        /// <param name="domain">The _domain_ associated to the account (optional)</param>
        /// <returns>RobotConfiguration</returns>
        RobotConfiguration RobotConfigurationGet (string username = default(string), string domain = default(string));

        /// <summary>
        /// Retrieve the Robot configuration
        /// </summary>
        /// <remarks>
        /// This API allows to retrieve the Robot configuration. 
        /// </remarks>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username">The _username_ associated to the account (optional)</param>
        /// <param name="domain">The _domain_ associated to the account (optional)</param>
        /// <returns>ApiResponse of RobotConfiguration</returns>
        ApiResponse<RobotConfiguration> RobotConfigurationGetWithHttpInfo (string username = default(string), string domain = default(string));
        /// <summary>
        /// Edit the Robot configuration
        /// </summary>
        /// <remarks>
        /// This API allows to edit the Robot configuration. 
        /// </remarks>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="robotConfiguration">RobotConfiguration.</param>
        /// <param name="username">The _username_ associated to the account (optional)</param>
        /// <param name="domain">The _domain_ associated to the account (optional)</param>
        /// <returns></returns>
        void RobotConfigurationPut (RobotConfiguration robotConfiguration, string username = default(string), string domain = default(string));

        /// <summary>
        /// Edit the Robot configuration
        /// </summary>
        /// <remarks>
        /// This API allows to edit the Robot configuration. 
        /// </remarks>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="robotConfiguration">RobotConfiguration.</param>
        /// <param name="username">The _username_ associated to the account (optional)</param>
        /// <param name="domain">The _domain_ associated to the account (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> RobotConfigurationPutWithHttpInfo (RobotConfiguration robotConfiguration, string username = default(string), string domain = default(string));
        /// <summary>
        /// Create a new DST in one call
        /// </summary>
        /// <remarks>
        /// This API allows to create a new DST with a more convenient interface for client applications. The purpose is to provide a method for the creation of a DST in order to semplify the integration into third part applications. 
        /// </remarks>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createDigitalSignatureTransaction">description</param>
        /// <returns>DigitalSignatureTransaction</returns>
        DigitalSignatureTransaction RobotDSTsPost (CreateDigitalSignatureTransaction createDigitalSignatureTransaction);

        /// <summary>
        /// Create a new DST in one call
        /// </summary>
        /// <remarks>
        /// This API allows to create a new DST with a more convenient interface for client applications. The purpose is to provide a method for the creation of a DST in order to semplify the integration into third part applications. 
        /// </remarks>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createDigitalSignatureTransaction">description</param>
        /// <returns>ApiResponse of DigitalSignatureTransaction</returns>
        ApiResponse<DigitalSignatureTransaction> RobotDSTsPostWithHttpInfo (CreateDigitalSignatureTransaction createDigitalSignatureTransaction);
        /// <summary>
        /// Instantiate a DST from a template by robot
        /// </summary>
        /// <remarks>
        /// This API allows to instantiate a DST from a template patching parts of its data structure. 
        /// </remarks>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The value of _the unique id_</param>
        /// <param name="instantiateDSTTemplate"></param>
        /// <returns>DigitalSignatureTransaction</returns>
        DigitalSignatureTransaction RobotIdInstantiatePost (Guid id, InstantiateDSTTemplate instantiateDSTTemplate);

        /// <summary>
        /// Instantiate a DST from a template by robot
        /// </summary>
        /// <remarks>
        /// This API allows to instantiate a DST from a template patching parts of its data structure. 
        /// </remarks>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The value of _the unique id_</param>
        /// <param name="instantiateDSTTemplate"></param>
        /// <returns>ApiResponse of DigitalSignatureTransaction</returns>
        ApiResponse<DigitalSignatureTransaction> RobotIdInstantiatePostWithHttpInfo (Guid id, InstantiateDSTTemplate instantiateDSTTemplate);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Clear a Robot authentication lifetime token
        /// </summary>
        /// <remarks>
        /// This API allows to clear the Robot authentication lifetime token.
        /// </remarks>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username">The _username_ associated to the account (optional)</param>
        /// <param name="domain">The _domain_ associated to the account (optional)</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task RobotAuthenticationDeleteAsync (string username = default(string), string domain = default(string));

        /// <summary>
        /// Clear a Robot authentication lifetime token
        /// </summary>
        /// <remarks>
        /// This API allows to clear the Robot authentication lifetime token.
        /// </remarks>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username">The _username_ associated to the account (optional)</param>
        /// <param name="domain">The _domain_ associated to the account (optional)</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> RobotAuthenticationDeleteAsyncWithHttpInfo (string username = default(string), string domain = default(string));
        /// <summary>
        /// Retrieve the Robot authentication lifetime token
        /// </summary>
        /// <remarks>
        /// This API allows to generate or retrieves the Robot authentication lifetime token for the specified robot account, or the current logged in account. 
        /// </remarks>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username">The _username_ associated to the account (optional)</param>
        /// <param name="domain">The _domain_ associated to the account (optional)</param>
        /// <returns>Task of RobotAuthenticationToken</returns>
        System.Threading.Tasks.Task<RobotAuthenticationToken> RobotAuthenticationGetAsync (string username = default(string), string domain = default(string));

        /// <summary>
        /// Retrieve the Robot authentication lifetime token
        /// </summary>
        /// <remarks>
        /// This API allows to generate or retrieves the Robot authentication lifetime token for the specified robot account, or the current logged in account. 
        /// </remarks>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username">The _username_ associated to the account (optional)</param>
        /// <param name="domain">The _domain_ associated to the account (optional)</param>
        /// <returns>Task of ApiResponse (RobotAuthenticationToken)</returns>
        System.Threading.Tasks.Task<ApiResponse<RobotAuthenticationToken>> RobotAuthenticationGetAsyncWithHttpInfo (string username = default(string), string domain = default(string));
        /// <summary>
        /// Retrieve the Robot configuration
        /// </summary>
        /// <remarks>
        /// This API allows to retrieve the Robot configuration. 
        /// </remarks>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username">The _username_ associated to the account (optional)</param>
        /// <param name="domain">The _domain_ associated to the account (optional)</param>
        /// <returns>Task of RobotConfiguration</returns>
        System.Threading.Tasks.Task<RobotConfiguration> RobotConfigurationGetAsync (string username = default(string), string domain = default(string));

        /// <summary>
        /// Retrieve the Robot configuration
        /// </summary>
        /// <remarks>
        /// This API allows to retrieve the Robot configuration. 
        /// </remarks>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username">The _username_ associated to the account (optional)</param>
        /// <param name="domain">The _domain_ associated to the account (optional)</param>
        /// <returns>Task of ApiResponse (RobotConfiguration)</returns>
        System.Threading.Tasks.Task<ApiResponse<RobotConfiguration>> RobotConfigurationGetAsyncWithHttpInfo (string username = default(string), string domain = default(string));
        /// <summary>
        /// Edit the Robot configuration
        /// </summary>
        /// <remarks>
        /// This API allows to edit the Robot configuration. 
        /// </remarks>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="robotConfiguration">RobotConfiguration.</param>
        /// <param name="username">The _username_ associated to the account (optional)</param>
        /// <param name="domain">The _domain_ associated to the account (optional)</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task RobotConfigurationPutAsync (RobotConfiguration robotConfiguration, string username = default(string), string domain = default(string));

        /// <summary>
        /// Edit the Robot configuration
        /// </summary>
        /// <remarks>
        /// This API allows to edit the Robot configuration. 
        /// </remarks>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="robotConfiguration">RobotConfiguration.</param>
        /// <param name="username">The _username_ associated to the account (optional)</param>
        /// <param name="domain">The _domain_ associated to the account (optional)</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> RobotConfigurationPutAsyncWithHttpInfo (RobotConfiguration robotConfiguration, string username = default(string), string domain = default(string));
        /// <summary>
        /// Create a new DST in one call
        /// </summary>
        /// <remarks>
        /// This API allows to create a new DST with a more convenient interface for client applications. The purpose is to provide a method for the creation of a DST in order to semplify the integration into third part applications. 
        /// </remarks>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createDigitalSignatureTransaction">description</param>
        /// <returns>Task of DigitalSignatureTransaction</returns>
        System.Threading.Tasks.Task<DigitalSignatureTransaction> RobotDSTsPostAsync (CreateDigitalSignatureTransaction createDigitalSignatureTransaction);

        /// <summary>
        /// Create a new DST in one call
        /// </summary>
        /// <remarks>
        /// This API allows to create a new DST with a more convenient interface for client applications. The purpose is to provide a method for the creation of a DST in order to semplify the integration into third part applications. 
        /// </remarks>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createDigitalSignatureTransaction">description</param>
        /// <returns>Task of ApiResponse (DigitalSignatureTransaction)</returns>
        System.Threading.Tasks.Task<ApiResponse<DigitalSignatureTransaction>> RobotDSTsPostAsyncWithHttpInfo (CreateDigitalSignatureTransaction createDigitalSignatureTransaction);
        /// <summary>
        /// Instantiate a DST from a template by robot
        /// </summary>
        /// <remarks>
        /// This API allows to instantiate a DST from a template patching parts of its data structure. 
        /// </remarks>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The value of _the unique id_</param>
        /// <param name="instantiateDSTTemplate"></param>
        /// <returns>Task of DigitalSignatureTransaction</returns>
        System.Threading.Tasks.Task<DigitalSignatureTransaction> RobotIdInstantiatePostAsync (Guid id, InstantiateDSTTemplate instantiateDSTTemplate);

        /// <summary>
        /// Instantiate a DST from a template by robot
        /// </summary>
        /// <remarks>
        /// This API allows to instantiate a DST from a template patching parts of its data structure. 
        /// </remarks>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The value of _the unique id_</param>
        /// <param name="instantiateDSTTemplate"></param>
        /// <returns>Task of ApiResponse (DigitalSignatureTransaction)</returns>
        System.Threading.Tasks.Task<ApiResponse<DigitalSignatureTransaction>> RobotIdInstantiatePostAsyncWithHttpInfo (Guid id, InstantiateDSTTemplate instantiateDSTTemplate);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class Bit4idPathgroupRobotsApi : IBit4idPathgroupRobotsApi
    {
        private SigningToday.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="Bit4idPathgroupRobotsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public Bit4idPathgroupRobotsApi(String basePath)
        {
            this.Configuration = new SigningToday.Client.Configuration { BasePath = basePath };

            ExceptionFactory = SigningToday.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Bit4idPathgroupRobotsApi"/> class
        /// </summary>
        /// <returns></returns>
        public Bit4idPathgroupRobotsApi()
        {
            this.Configuration = SigningToday.Client.Configuration.Default;

            ExceptionFactory = SigningToday.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Bit4idPathgroupRobotsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public Bit4idPathgroupRobotsApi(SigningToday.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = SigningToday.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = SigningToday.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public SigningToday.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public SigningToday.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Clear a Robot authentication lifetime token This API allows to clear the Robot authentication lifetime token.
        /// </summary>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username">The _username_ associated to the account (optional)</param>
        /// <param name="domain">The _domain_ associated to the account (optional)</param>
        /// <returns></returns>
        public void RobotAuthenticationDelete (string username = default(string), string domain = default(string))
        {
             RobotAuthenticationDeleteWithHttpInfo(username, domain);
        }

        /// <summary>
        /// Clear a Robot authentication lifetime token This API allows to clear the Robot authentication lifetime token.
        /// </summary>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username">The _username_ associated to the account (optional)</param>
        /// <param name="domain">The _domain_ associated to the account (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> RobotAuthenticationDeleteWithHttpInfo (string username = default(string), string domain = default(string))
        {

            var localVarPath = "/robot/authentication";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (username != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "username", username)); // query parameter
            if (domain != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "domain", domain)); // query parameter

            // authentication (OAuth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RobotAuthenticationDelete", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        /// Clear a Robot authentication lifetime token This API allows to clear the Robot authentication lifetime token.
        /// </summary>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username">The _username_ associated to the account (optional)</param>
        /// <param name="domain">The _domain_ associated to the account (optional)</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task RobotAuthenticationDeleteAsync (string username = default(string), string domain = default(string))
        {
             await RobotAuthenticationDeleteAsyncWithHttpInfo(username, domain);

        }

        /// <summary>
        /// Clear a Robot authentication lifetime token This API allows to clear the Robot authentication lifetime token.
        /// </summary>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username">The _username_ associated to the account (optional)</param>
        /// <param name="domain">The _domain_ associated to the account (optional)</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> RobotAuthenticationDeleteAsyncWithHttpInfo (string username = default(string), string domain = default(string))
        {

            var localVarPath = "/robot/authentication";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (username != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "username", username)); // query parameter
            if (domain != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "domain", domain)); // query parameter

            // authentication (OAuth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RobotAuthenticationDelete", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        /// Retrieve the Robot authentication lifetime token This API allows to generate or retrieves the Robot authentication lifetime token for the specified robot account, or the current logged in account. 
        /// </summary>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username">The _username_ associated to the account (optional)</param>
        /// <param name="domain">The _domain_ associated to the account (optional)</param>
        /// <returns>RobotAuthenticationToken</returns>
        public RobotAuthenticationToken RobotAuthenticationGet (string username = default(string), string domain = default(string))
        {
             ApiResponse<RobotAuthenticationToken> localVarResponse = RobotAuthenticationGetWithHttpInfo(username, domain);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieve the Robot authentication lifetime token This API allows to generate or retrieves the Robot authentication lifetime token for the specified robot account, or the current logged in account. 
        /// </summary>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username">The _username_ associated to the account (optional)</param>
        /// <param name="domain">The _domain_ associated to the account (optional)</param>
        /// <returns>ApiResponse of RobotAuthenticationToken</returns>
        public ApiResponse<RobotAuthenticationToken> RobotAuthenticationGetWithHttpInfo (string username = default(string), string domain = default(string))
        {

            var localVarPath = "/robot/authentication";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "*/*"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (username != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "username", username)); // query parameter
            if (domain != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "domain", domain)); // query parameter

            // authentication (OAuth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RobotAuthenticationGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<RobotAuthenticationToken>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (RobotAuthenticationToken) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(RobotAuthenticationToken)));
        }

        /// <summary>
        /// Retrieve the Robot authentication lifetime token This API allows to generate or retrieves the Robot authentication lifetime token for the specified robot account, or the current logged in account. 
        /// </summary>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username">The _username_ associated to the account (optional)</param>
        /// <param name="domain">The _domain_ associated to the account (optional)</param>
        /// <returns>Task of RobotAuthenticationToken</returns>
        public async System.Threading.Tasks.Task<RobotAuthenticationToken> RobotAuthenticationGetAsync (string username = default(string), string domain = default(string))
        {
             ApiResponse<RobotAuthenticationToken> localVarResponse = await RobotAuthenticationGetAsyncWithHttpInfo(username, domain);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Retrieve the Robot authentication lifetime token This API allows to generate or retrieves the Robot authentication lifetime token for the specified robot account, or the current logged in account. 
        /// </summary>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username">The _username_ associated to the account (optional)</param>
        /// <param name="domain">The _domain_ associated to the account (optional)</param>
        /// <returns>Task of ApiResponse (RobotAuthenticationToken)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<RobotAuthenticationToken>> RobotAuthenticationGetAsyncWithHttpInfo (string username = default(string), string domain = default(string))
        {

            var localVarPath = "/robot/authentication";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "*/*"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (username != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "username", username)); // query parameter
            if (domain != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "domain", domain)); // query parameter

            // authentication (OAuth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RobotAuthenticationGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<RobotAuthenticationToken>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (RobotAuthenticationToken) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(RobotAuthenticationToken)));
        }

        /// <summary>
        /// Retrieve the Robot configuration This API allows to retrieve the Robot configuration. 
        /// </summary>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username">The _username_ associated to the account (optional)</param>
        /// <param name="domain">The _domain_ associated to the account (optional)</param>
        /// <returns>RobotConfiguration</returns>
        public RobotConfiguration RobotConfigurationGet (string username = default(string), string domain = default(string))
        {
             ApiResponse<RobotConfiguration> localVarResponse = RobotConfigurationGetWithHttpInfo(username, domain);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieve the Robot configuration This API allows to retrieve the Robot configuration. 
        /// </summary>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username">The _username_ associated to the account (optional)</param>
        /// <param name="domain">The _domain_ associated to the account (optional)</param>
        /// <returns>ApiResponse of RobotConfiguration</returns>
        public ApiResponse<RobotConfiguration> RobotConfigurationGetWithHttpInfo (string username = default(string), string domain = default(string))
        {

            var localVarPath = "/robot/configuration";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "*/*"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (username != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "username", username)); // query parameter
            if (domain != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "domain", domain)); // query parameter

            // authentication (OAuth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RobotConfigurationGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<RobotConfiguration>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (RobotConfiguration) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(RobotConfiguration)));
        }

        /// <summary>
        /// Retrieve the Robot configuration This API allows to retrieve the Robot configuration. 
        /// </summary>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username">The _username_ associated to the account (optional)</param>
        /// <param name="domain">The _domain_ associated to the account (optional)</param>
        /// <returns>Task of RobotConfiguration</returns>
        public async System.Threading.Tasks.Task<RobotConfiguration> RobotConfigurationGetAsync (string username = default(string), string domain = default(string))
        {
             ApiResponse<RobotConfiguration> localVarResponse = await RobotConfigurationGetAsyncWithHttpInfo(username, domain);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Retrieve the Robot configuration This API allows to retrieve the Robot configuration. 
        /// </summary>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username">The _username_ associated to the account (optional)</param>
        /// <param name="domain">The _domain_ associated to the account (optional)</param>
        /// <returns>Task of ApiResponse (RobotConfiguration)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<RobotConfiguration>> RobotConfigurationGetAsyncWithHttpInfo (string username = default(string), string domain = default(string))
        {

            var localVarPath = "/robot/configuration";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "*/*"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (username != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "username", username)); // query parameter
            if (domain != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "domain", domain)); // query parameter

            // authentication (OAuth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RobotConfigurationGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<RobotConfiguration>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (RobotConfiguration) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(RobotConfiguration)));
        }

        /// <summary>
        /// Edit the Robot configuration This API allows to edit the Robot configuration. 
        /// </summary>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="robotConfiguration">RobotConfiguration.</param>
        /// <param name="username">The _username_ associated to the account (optional)</param>
        /// <param name="domain">The _domain_ associated to the account (optional)</param>
        /// <returns></returns>
        public void RobotConfigurationPut (RobotConfiguration robotConfiguration, string username = default(string), string domain = default(string))
        {
             RobotConfigurationPutWithHttpInfo(robotConfiguration, username, domain);
        }

        /// <summary>
        /// Edit the Robot configuration This API allows to edit the Robot configuration. 
        /// </summary>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="robotConfiguration">RobotConfiguration.</param>
        /// <param name="username">The _username_ associated to the account (optional)</param>
        /// <param name="domain">The _domain_ associated to the account (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> RobotConfigurationPutWithHttpInfo (RobotConfiguration robotConfiguration, string username = default(string), string domain = default(string))
        {
            // verify the required parameter 'robotConfiguration' is set
            if (robotConfiguration == null)
                throw new ApiException(400, "Missing required parameter 'robotConfiguration' when calling Bit4idPathgroupRobotsApi->RobotConfigurationPut");

            var localVarPath = "/robot/configuration";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (username != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "username", username)); // query parameter
            if (domain != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "domain", domain)); // query parameter
            if (robotConfiguration != null && robotConfiguration.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(robotConfiguration); // http body (model) parameter
            }
            else
            {
                localVarPostBody = robotConfiguration; // byte array
            }

            // authentication (OAuth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RobotConfigurationPut", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        /// Edit the Robot configuration This API allows to edit the Robot configuration. 
        /// </summary>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="robotConfiguration">RobotConfiguration.</param>
        /// <param name="username">The _username_ associated to the account (optional)</param>
        /// <param name="domain">The _domain_ associated to the account (optional)</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task RobotConfigurationPutAsync (RobotConfiguration robotConfiguration, string username = default(string), string domain = default(string))
        {
             await RobotConfigurationPutAsyncWithHttpInfo(robotConfiguration, username, domain);

        }

        /// <summary>
        /// Edit the Robot configuration This API allows to edit the Robot configuration. 
        /// </summary>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="robotConfiguration">RobotConfiguration.</param>
        /// <param name="username">The _username_ associated to the account (optional)</param>
        /// <param name="domain">The _domain_ associated to the account (optional)</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> RobotConfigurationPutAsyncWithHttpInfo (RobotConfiguration robotConfiguration, string username = default(string), string domain = default(string))
        {
            // verify the required parameter 'robotConfiguration' is set
            if (robotConfiguration == null)
                throw new ApiException(400, "Missing required parameter 'robotConfiguration' when calling Bit4idPathgroupRobotsApi->RobotConfigurationPut");

            var localVarPath = "/robot/configuration";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (username != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "username", username)); // query parameter
            if (domain != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "domain", domain)); // query parameter
            if (robotConfiguration != null && robotConfiguration.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(robotConfiguration); // http body (model) parameter
            }
            else
            {
                localVarPostBody = robotConfiguration; // byte array
            }

            // authentication (OAuth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RobotConfigurationPut", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        /// Create a new DST in one call This API allows to create a new DST with a more convenient interface for client applications. The purpose is to provide a method for the creation of a DST in order to semplify the integration into third part applications. 
        /// </summary>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createDigitalSignatureTransaction">description</param>
        /// <returns>DigitalSignatureTransaction</returns>
        public DigitalSignatureTransaction RobotDSTsPost (CreateDigitalSignatureTransaction createDigitalSignatureTransaction)
        {
             ApiResponse<DigitalSignatureTransaction> localVarResponse = RobotDSTsPostWithHttpInfo(createDigitalSignatureTransaction);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Create a new DST in one call This API allows to create a new DST with a more convenient interface for client applications. The purpose is to provide a method for the creation of a DST in order to semplify the integration into third part applications. 
        /// </summary>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createDigitalSignatureTransaction">description</param>
        /// <returns>ApiResponse of DigitalSignatureTransaction</returns>
        public ApiResponse<DigitalSignatureTransaction> RobotDSTsPostWithHttpInfo (CreateDigitalSignatureTransaction createDigitalSignatureTransaction)
        {
            // verify the required parameter 'createDigitalSignatureTransaction' is set
            if (createDigitalSignatureTransaction == null)
                throw new ApiException(400, "Missing required parameter 'createDigitalSignatureTransaction' when calling Bit4idPathgroupRobotsApi->RobotDSTsPost");

            var localVarPath = "/robot/DSTs";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "*/*"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (createDigitalSignatureTransaction != null && createDigitalSignatureTransaction.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(createDigitalSignatureTransaction); // http body (model) parameter
            }
            else
            {
                localVarPostBody = createDigitalSignatureTransaction; // byte array
            }

            // authentication (OAuth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RobotDSTsPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DigitalSignatureTransaction>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (DigitalSignatureTransaction) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DigitalSignatureTransaction)));
        }

        /// <summary>
        /// Create a new DST in one call This API allows to create a new DST with a more convenient interface for client applications. The purpose is to provide a method for the creation of a DST in order to semplify the integration into third part applications. 
        /// </summary>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createDigitalSignatureTransaction">description</param>
        /// <returns>Task of DigitalSignatureTransaction</returns>
        public async System.Threading.Tasks.Task<DigitalSignatureTransaction> RobotDSTsPostAsync (CreateDigitalSignatureTransaction createDigitalSignatureTransaction)
        {
             ApiResponse<DigitalSignatureTransaction> localVarResponse = await RobotDSTsPostAsyncWithHttpInfo(createDigitalSignatureTransaction);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Create a new DST in one call This API allows to create a new DST with a more convenient interface for client applications. The purpose is to provide a method for the creation of a DST in order to semplify the integration into third part applications. 
        /// </summary>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createDigitalSignatureTransaction">description</param>
        /// <returns>Task of ApiResponse (DigitalSignatureTransaction)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<DigitalSignatureTransaction>> RobotDSTsPostAsyncWithHttpInfo (CreateDigitalSignatureTransaction createDigitalSignatureTransaction)
        {
            // verify the required parameter 'createDigitalSignatureTransaction' is set
            if (createDigitalSignatureTransaction == null)
                throw new ApiException(400, "Missing required parameter 'createDigitalSignatureTransaction' when calling Bit4idPathgroupRobotsApi->RobotDSTsPost");

            var localVarPath = "/robot/DSTs";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "*/*"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (createDigitalSignatureTransaction != null && createDigitalSignatureTransaction.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(createDigitalSignatureTransaction); // http body (model) parameter
            }
            else
            {
                localVarPostBody = createDigitalSignatureTransaction; // byte array
            }

            // authentication (OAuth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RobotDSTsPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DigitalSignatureTransaction>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (DigitalSignatureTransaction) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DigitalSignatureTransaction)));
        }

        /// <summary>
        /// Instantiate a DST from a template by robot This API allows to instantiate a DST from a template patching parts of its data structure. 
        /// </summary>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The value of _the unique id_</param>
        /// <param name="instantiateDSTTemplate"></param>
        /// <returns>DigitalSignatureTransaction</returns>
        public DigitalSignatureTransaction RobotIdInstantiatePost (Guid id, InstantiateDSTTemplate instantiateDSTTemplate)
        {
             ApiResponse<DigitalSignatureTransaction> localVarResponse = RobotIdInstantiatePostWithHttpInfo(id, instantiateDSTTemplate);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Instantiate a DST from a template by robot This API allows to instantiate a DST from a template patching parts of its data structure. 
        /// </summary>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The value of _the unique id_</param>
        /// <param name="instantiateDSTTemplate"></param>
        /// <returns>ApiResponse of DigitalSignatureTransaction</returns>
        public ApiResponse<DigitalSignatureTransaction> RobotIdInstantiatePostWithHttpInfo (Guid id, InstantiateDSTTemplate instantiateDSTTemplate)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling Bit4idPathgroupRobotsApi->RobotIdInstantiatePost");
            // verify the required parameter 'instantiateDSTTemplate' is set
            if (instantiateDSTTemplate == null)
                throw new ApiException(400, "Missing required parameter 'instantiateDSTTemplate' when calling Bit4idPathgroupRobotsApi->RobotIdInstantiatePost");

            var localVarPath = "/robot/{id}/instantiate";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "*/*"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (instantiateDSTTemplate != null && instantiateDSTTemplate.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(instantiateDSTTemplate); // http body (model) parameter
            }
            else
            {
                localVarPostBody = instantiateDSTTemplate; // byte array
            }

            // authentication (OAuth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RobotIdInstantiatePost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DigitalSignatureTransaction>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (DigitalSignatureTransaction) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DigitalSignatureTransaction)));
        }

        /// <summary>
        /// Instantiate a DST from a template by robot This API allows to instantiate a DST from a template patching parts of its data structure. 
        /// </summary>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The value of _the unique id_</param>
        /// <param name="instantiateDSTTemplate"></param>
        /// <returns>Task of DigitalSignatureTransaction</returns>
        public async System.Threading.Tasks.Task<DigitalSignatureTransaction> RobotIdInstantiatePostAsync (Guid id, InstantiateDSTTemplate instantiateDSTTemplate)
        {
             ApiResponse<DigitalSignatureTransaction> localVarResponse = await RobotIdInstantiatePostAsyncWithHttpInfo(id, instantiateDSTTemplate);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Instantiate a DST from a template by robot This API allows to instantiate a DST from a template patching parts of its data structure. 
        /// </summary>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The value of _the unique id_</param>
        /// <param name="instantiateDSTTemplate"></param>
        /// <returns>Task of ApiResponse (DigitalSignatureTransaction)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<DigitalSignatureTransaction>> RobotIdInstantiatePostAsyncWithHttpInfo (Guid id, InstantiateDSTTemplate instantiateDSTTemplate)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling Bit4idPathgroupRobotsApi->RobotIdInstantiatePost");
            // verify the required parameter 'instantiateDSTTemplate' is set
            if (instantiateDSTTemplate == null)
                throw new ApiException(400, "Missing required parameter 'instantiateDSTTemplate' when calling Bit4idPathgroupRobotsApi->RobotIdInstantiatePost");

            var localVarPath = "/robot/{id}/instantiate";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "*/*"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (instantiateDSTTemplate != null && instantiateDSTTemplate.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(instantiateDSTTemplate); // http body (model) parameter
            }
            else
            {
                localVarPostBody = instantiateDSTTemplate; // byte array
            }

            // authentication (OAuth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RobotIdInstantiatePost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DigitalSignatureTransaction>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (DigitalSignatureTransaction) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DigitalSignatureTransaction)));
        }

    }
}
