/* 
 * Signing Today Web
 *
 * *Signing Today* is the perfect Digital Signature Gateway. Whenever in Your workflow You need to add one or more Digital Signatures to Your document, *Signing Today* is the right choice. You prepare Your documents, *Signing Today* takes care of all the rest: send invitations (`signature tickets`) to signers, collects their signatures, send You back the signed document. Integrating *Signing Today* in Your existing applications is very easy. Just follow these API specifications and get inspired by the many examples presented hereafter. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using SigningToday.Client;
using SigningToday.Model;

namespace SigningToday.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDevicesApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Clear a trusted device
        /// </summary>
        /// <remarks>
        /// This APIs allows to deregister a _deviceId_ of a trusted device.  It also deletes any notification push-token associated to the trusted device. 
        /// </remarks>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">The _deviceId_ to deregister</param>
        /// <param name="userId">Select the objects relative to the user specified by the parameter. If not specified will be used the id of the current authenticated user (optional)</param>
        /// <returns></returns>
        void DeviceAuthorizationDelete (string deviceId, Guid userId = default(Guid));

        /// <summary>
        /// Clear a trusted device
        /// </summary>
        /// <remarks>
        /// This APIs allows to deregister a _deviceId_ of a trusted device.  It also deletes any notification push-token associated to the trusted device. 
        /// </remarks>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">The _deviceId_ to deregister</param>
        /// <param name="userId">Select the objects relative to the user specified by the parameter. If not specified will be used the id of the current authenticated user (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> DeviceAuthorizationDeleteWithHttpInfo (string deviceId, Guid userId = default(Guid));
        /// <summary>
        /// Retrieve a challenge for authorizing a new trusted device
        /// </summary>
        /// <remarks>
        /// This API allows to retrieve a challenge in order to authorize a new trusted device.   - If asked in image/png the challenge is given encoded as a QR-Code image.   - An invocation of the endpoint invalidate any previous challenge.   - The challenge lasts 10 minutes. 
        /// </remarks>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>DeviceAuthorizationResponse</returns>
        DeviceAuthorizationResponse DeviceAuthorizationGet ();

        /// <summary>
        /// Retrieve a challenge for authorizing a new trusted device
        /// </summary>
        /// <remarks>
        /// This API allows to retrieve a challenge in order to authorize a new trusted device.   - If asked in image/png the challenge is given encoded as a QR-Code image.   - An invocation of the endpoint invalidate any previous challenge.   - The challenge lasts 10 minutes. 
        /// </remarks>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of DeviceAuthorizationResponse</returns>
        ApiResponse<DeviceAuthorizationResponse> DeviceAuthorizationGetWithHttpInfo ();
        /// <summary>
        /// Register a new trusted device
        /// </summary>
        /// <remarks>
        /// This API allows to register a new trusted device. If the device is already present, it returns the current associated Token and updates the name. 
        /// </remarks>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inlineObject7"></param>
        /// <returns>List&lt;Guid&gt;</returns>
        List<Guid> DeviceAuthorizationPost (InlineObject7 inlineObject7);

        /// <summary>
        /// Register a new trusted device
        /// </summary>
        /// <remarks>
        /// This API allows to register a new trusted device. If the device is already present, it returns the current associated Token and updates the name. 
        /// </remarks>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inlineObject7"></param>
        /// <returns>ApiResponse of List&lt;Guid&gt;</returns>
        ApiResponse<List<Guid>> DeviceAuthorizationPostWithHttpInfo (InlineObject7 inlineObject7);
        /// <summary>
        /// Get the list of trusted devices
        /// </summary>
        /// <remarks>
        /// The API allows to enumerate all the devices of a user. 
        /// </remarks>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">Select the objects relative to the user specified by the parameter. If not specified will be used the id of the current authenticated user (optional)</param>
        /// <param name="top">A number of results to return. Applied after **$skip**  (optional)</param>
        /// <param name="skip">An offset into the collection of results (optional)</param>
        /// <param name="count">If true, the server includes the count of all the items in the response  (optional)</param>
        /// <returns>TrustedDevicesGetResponse</returns>
        TrustedDevicesGetResponse DevicesGet (Guid userId = default(Guid), int top = default(int), long skip = default(long), bool count = default(bool));

        /// <summary>
        /// Get the list of trusted devices
        /// </summary>
        /// <remarks>
        /// The API allows to enumerate all the devices of a user. 
        /// </remarks>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">Select the objects relative to the user specified by the parameter. If not specified will be used the id of the current authenticated user (optional)</param>
        /// <param name="top">A number of results to return. Applied after **$skip**  (optional)</param>
        /// <param name="skip">An offset into the collection of results (optional)</param>
        /// <param name="count">If true, the server includes the count of all the items in the response  (optional)</param>
        /// <returns>ApiResponse of TrustedDevicesGetResponse</returns>
        ApiResponse<TrustedDevicesGetResponse> DevicesGetWithHttpInfo (Guid userId = default(Guid), int top = default(int), long skip = default(long), bool count = default(bool));
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Clear a trusted device
        /// </summary>
        /// <remarks>
        /// This APIs allows to deregister a _deviceId_ of a trusted device.  It also deletes any notification push-token associated to the trusted device. 
        /// </remarks>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">The _deviceId_ to deregister</param>
        /// <param name="userId">Select the objects relative to the user specified by the parameter. If not specified will be used the id of the current authenticated user (optional)</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task DeviceAuthorizationDeleteAsync (string deviceId, Guid userId = default(Guid));

        /// <summary>
        /// Clear a trusted device
        /// </summary>
        /// <remarks>
        /// This APIs allows to deregister a _deviceId_ of a trusted device.  It also deletes any notification push-token associated to the trusted device. 
        /// </remarks>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">The _deviceId_ to deregister</param>
        /// <param name="userId">Select the objects relative to the user specified by the parameter. If not specified will be used the id of the current authenticated user (optional)</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DeviceAuthorizationDeleteAsyncWithHttpInfo (string deviceId, Guid userId = default(Guid));
        /// <summary>
        /// Retrieve a challenge for authorizing a new trusted device
        /// </summary>
        /// <remarks>
        /// This API allows to retrieve a challenge in order to authorize a new trusted device.   - If asked in image/png the challenge is given encoded as a QR-Code image.   - An invocation of the endpoint invalidate any previous challenge.   - The challenge lasts 10 minutes. 
        /// </remarks>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of DeviceAuthorizationResponse</returns>
        System.Threading.Tasks.Task<DeviceAuthorizationResponse> DeviceAuthorizationGetAsync ();

        /// <summary>
        /// Retrieve a challenge for authorizing a new trusted device
        /// </summary>
        /// <remarks>
        /// This API allows to retrieve a challenge in order to authorize a new trusted device.   - If asked in image/png the challenge is given encoded as a QR-Code image.   - An invocation of the endpoint invalidate any previous challenge.   - The challenge lasts 10 minutes. 
        /// </remarks>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (DeviceAuthorizationResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<DeviceAuthorizationResponse>> DeviceAuthorizationGetAsyncWithHttpInfo ();
        /// <summary>
        /// Register a new trusted device
        /// </summary>
        /// <remarks>
        /// This API allows to register a new trusted device. If the device is already present, it returns the current associated Token and updates the name. 
        /// </remarks>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inlineObject7"></param>
        /// <returns>Task of List&lt;Guid&gt;</returns>
        System.Threading.Tasks.Task<List<Guid>> DeviceAuthorizationPostAsync (InlineObject7 inlineObject7);

        /// <summary>
        /// Register a new trusted device
        /// </summary>
        /// <remarks>
        /// This API allows to register a new trusted device. If the device is already present, it returns the current associated Token and updates the name. 
        /// </remarks>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inlineObject7"></param>
        /// <returns>Task of ApiResponse (List&lt;Guid&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<Guid>>> DeviceAuthorizationPostAsyncWithHttpInfo (InlineObject7 inlineObject7);
        /// <summary>
        /// Get the list of trusted devices
        /// </summary>
        /// <remarks>
        /// The API allows to enumerate all the devices of a user. 
        /// </remarks>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">Select the objects relative to the user specified by the parameter. If not specified will be used the id of the current authenticated user (optional)</param>
        /// <param name="top">A number of results to return. Applied after **$skip**  (optional)</param>
        /// <param name="skip">An offset into the collection of results (optional)</param>
        /// <param name="count">If true, the server includes the count of all the items in the response  (optional)</param>
        /// <returns>Task of TrustedDevicesGetResponse</returns>
        System.Threading.Tasks.Task<TrustedDevicesGetResponse> DevicesGetAsync (Guid userId = default(Guid), int top = default(int), long skip = default(long), bool count = default(bool));

        /// <summary>
        /// Get the list of trusted devices
        /// </summary>
        /// <remarks>
        /// The API allows to enumerate all the devices of a user. 
        /// </remarks>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">Select the objects relative to the user specified by the parameter. If not specified will be used the id of the current authenticated user (optional)</param>
        /// <param name="top">A number of results to return. Applied after **$skip**  (optional)</param>
        /// <param name="skip">An offset into the collection of results (optional)</param>
        /// <param name="count">If true, the server includes the count of all the items in the response  (optional)</param>
        /// <returns>Task of ApiResponse (TrustedDevicesGetResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<TrustedDevicesGetResponse>> DevicesGetAsyncWithHttpInfo (Guid userId = default(Guid), int top = default(int), long skip = default(long), bool count = default(bool));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class DevicesApi : IDevicesApi
    {
        private SigningToday.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="DevicesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DevicesApi(String basePath)
        {
            this.Configuration = new SigningToday.Client.Configuration { BasePath = basePath };

            ExceptionFactory = SigningToday.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DevicesApi"/> class
        /// </summary>
        /// <returns></returns>
        public DevicesApi()
        {
            this.Configuration = SigningToday.Client.Configuration.Default;

            ExceptionFactory = SigningToday.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DevicesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public DevicesApi(SigningToday.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = SigningToday.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = SigningToday.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public SigningToday.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public SigningToday.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Clear a trusted device This APIs allows to deregister a _deviceId_ of a trusted device.  It also deletes any notification push-token associated to the trusted device. 
        /// </summary>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">The _deviceId_ to deregister</param>
        /// <param name="userId">Select the objects relative to the user specified by the parameter. If not specified will be used the id of the current authenticated user (optional)</param>
        /// <returns></returns>
        public void DeviceAuthorizationDelete (string deviceId, Guid userId = default(Guid))
        {
             DeviceAuthorizationDeleteWithHttpInfo(deviceId, userId);
        }

        /// <summary>
        /// Clear a trusted device This APIs allows to deregister a _deviceId_ of a trusted device.  It also deletes any notification push-token associated to the trusted device. 
        /// </summary>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">The _deviceId_ to deregister</param>
        /// <param name="userId">Select the objects relative to the user specified by the parameter. If not specified will be used the id of the current authenticated user (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> DeviceAuthorizationDeleteWithHttpInfo (string deviceId, Guid userId = default(Guid))
        {
            // verify the required parameter 'deviceId' is set
            if (deviceId == null)
                throw new ApiException(400, "Missing required parameter 'deviceId' when calling DevicesApi->DeviceAuthorizationDelete");

            var localVarPath = "/device/authorization";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (deviceId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "deviceId", deviceId)); // query parameter
            if (userId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "userId", userId)); // query parameter

            // authentication (OAuth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeviceAuthorizationDelete", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        /// Clear a trusted device This APIs allows to deregister a _deviceId_ of a trusted device.  It also deletes any notification push-token associated to the trusted device. 
        /// </summary>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">The _deviceId_ to deregister</param>
        /// <param name="userId">Select the objects relative to the user specified by the parameter. If not specified will be used the id of the current authenticated user (optional)</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task DeviceAuthorizationDeleteAsync (string deviceId, Guid userId = default(Guid))
        {
             await DeviceAuthorizationDeleteAsyncWithHttpInfo(deviceId, userId);

        }

        /// <summary>
        /// Clear a trusted device This APIs allows to deregister a _deviceId_ of a trusted device.  It also deletes any notification push-token associated to the trusted device. 
        /// </summary>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deviceId">The _deviceId_ to deregister</param>
        /// <param name="userId">Select the objects relative to the user specified by the parameter. If not specified will be used the id of the current authenticated user (optional)</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> DeviceAuthorizationDeleteAsyncWithHttpInfo (string deviceId, Guid userId = default(Guid))
        {
            // verify the required parameter 'deviceId' is set
            if (deviceId == null)
                throw new ApiException(400, "Missing required parameter 'deviceId' when calling DevicesApi->DeviceAuthorizationDelete");

            var localVarPath = "/device/authorization";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (deviceId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "deviceId", deviceId)); // query parameter
            if (userId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "userId", userId)); // query parameter

            // authentication (OAuth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeviceAuthorizationDelete", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        /// Retrieve a challenge for authorizing a new trusted device This API allows to retrieve a challenge in order to authorize a new trusted device.   - If asked in image/png the challenge is given encoded as a QR-Code image.   - An invocation of the endpoint invalidate any previous challenge.   - The challenge lasts 10 minutes. 
        /// </summary>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>DeviceAuthorizationResponse</returns>
        public DeviceAuthorizationResponse DeviceAuthorizationGet ()
        {
             ApiResponse<DeviceAuthorizationResponse> localVarResponse = DeviceAuthorizationGetWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieve a challenge for authorizing a new trusted device This API allows to retrieve a challenge in order to authorize a new trusted device.   - If asked in image/png the challenge is given encoded as a QR-Code image.   - An invocation of the endpoint invalidate any previous challenge.   - The challenge lasts 10 minutes. 
        /// </summary>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of DeviceAuthorizationResponse</returns>
        public ApiResponse<DeviceAuthorizationResponse> DeviceAuthorizationGetWithHttpInfo ()
        {

            var localVarPath = "/device/authorization";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "image/png",
                "*/*"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // authentication (OAuth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeviceAuthorizationGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DeviceAuthorizationResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (DeviceAuthorizationResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DeviceAuthorizationResponse)));
        }

        /// <summary>
        /// Retrieve a challenge for authorizing a new trusted device This API allows to retrieve a challenge in order to authorize a new trusted device.   - If asked in image/png the challenge is given encoded as a QR-Code image.   - An invocation of the endpoint invalidate any previous challenge.   - The challenge lasts 10 minutes. 
        /// </summary>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of DeviceAuthorizationResponse</returns>
        public async System.Threading.Tasks.Task<DeviceAuthorizationResponse> DeviceAuthorizationGetAsync ()
        {
             ApiResponse<DeviceAuthorizationResponse> localVarResponse = await DeviceAuthorizationGetAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// Retrieve a challenge for authorizing a new trusted device This API allows to retrieve a challenge in order to authorize a new trusted device.   - If asked in image/png the challenge is given encoded as a QR-Code image.   - An invocation of the endpoint invalidate any previous challenge.   - The challenge lasts 10 minutes. 
        /// </summary>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (DeviceAuthorizationResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<DeviceAuthorizationResponse>> DeviceAuthorizationGetAsyncWithHttpInfo ()
        {

            var localVarPath = "/device/authorization";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "image/png",
                "*/*"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // authentication (OAuth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeviceAuthorizationGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DeviceAuthorizationResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (DeviceAuthorizationResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DeviceAuthorizationResponse)));
        }

        /// <summary>
        /// Register a new trusted device This API allows to register a new trusted device. If the device is already present, it returns the current associated Token and updates the name. 
        /// </summary>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inlineObject7"></param>
        /// <returns>List&lt;Guid&gt;</returns>
        public List<Guid> DeviceAuthorizationPost (InlineObject7 inlineObject7)
        {
             ApiResponse<List<Guid>> localVarResponse = DeviceAuthorizationPostWithHttpInfo(inlineObject7);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Register a new trusted device This API allows to register a new trusted device. If the device is already present, it returns the current associated Token and updates the name. 
        /// </summary>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inlineObject7"></param>
        /// <returns>ApiResponse of List&lt;Guid&gt;</returns>
        public ApiResponse<List<Guid>> DeviceAuthorizationPostWithHttpInfo (InlineObject7 inlineObject7)
        {
            // verify the required parameter 'inlineObject7' is set
            if (inlineObject7 == null)
                throw new ApiException(400, "Missing required parameter 'inlineObject7' when calling DevicesApi->DeviceAuthorizationPost");

            var localVarPath = "/device/authorization";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "*/*"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (inlineObject7 != null && inlineObject7.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(inlineObject7); // http body (model) parameter
            }
            else
            {
                localVarPostBody = inlineObject7; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeviceAuthorizationPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<Guid>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<Guid>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<Guid>)));
        }

        /// <summary>
        /// Register a new trusted device This API allows to register a new trusted device. If the device is already present, it returns the current associated Token and updates the name. 
        /// </summary>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inlineObject7"></param>
        /// <returns>Task of List&lt;Guid&gt;</returns>
        public async System.Threading.Tasks.Task<List<Guid>> DeviceAuthorizationPostAsync (InlineObject7 inlineObject7)
        {
             ApiResponse<List<Guid>> localVarResponse = await DeviceAuthorizationPostAsyncWithHttpInfo(inlineObject7);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Register a new trusted device This API allows to register a new trusted device. If the device is already present, it returns the current associated Token and updates the name. 
        /// </summary>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inlineObject7"></param>
        /// <returns>Task of ApiResponse (List&lt;Guid&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<Guid>>> DeviceAuthorizationPostAsyncWithHttpInfo (InlineObject7 inlineObject7)
        {
            // verify the required parameter 'inlineObject7' is set
            if (inlineObject7 == null)
                throw new ApiException(400, "Missing required parameter 'inlineObject7' when calling DevicesApi->DeviceAuthorizationPost");

            var localVarPath = "/device/authorization";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "*/*"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (inlineObject7 != null && inlineObject7.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(inlineObject7); // http body (model) parameter
            }
            else
            {
                localVarPostBody = inlineObject7; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeviceAuthorizationPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<Guid>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<Guid>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<Guid>)));
        }

        /// <summary>
        /// Get the list of trusted devices The API allows to enumerate all the devices of a user. 
        /// </summary>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">Select the objects relative to the user specified by the parameter. If not specified will be used the id of the current authenticated user (optional)</param>
        /// <param name="top">A number of results to return. Applied after **$skip**  (optional)</param>
        /// <param name="skip">An offset into the collection of results (optional)</param>
        /// <param name="count">If true, the server includes the count of all the items in the response  (optional)</param>
        /// <returns>TrustedDevicesGetResponse</returns>
        public TrustedDevicesGetResponse DevicesGet (Guid userId = default(Guid), int top = default(int), long skip = default(long), bool count = default(bool))
        {
             ApiResponse<TrustedDevicesGetResponse> localVarResponse = DevicesGetWithHttpInfo(userId, top, skip, count);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get the list of trusted devices The API allows to enumerate all the devices of a user. 
        /// </summary>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">Select the objects relative to the user specified by the parameter. If not specified will be used the id of the current authenticated user (optional)</param>
        /// <param name="top">A number of results to return. Applied after **$skip**  (optional)</param>
        /// <param name="skip">An offset into the collection of results (optional)</param>
        /// <param name="count">If true, the server includes the count of all the items in the response  (optional)</param>
        /// <returns>ApiResponse of TrustedDevicesGetResponse</returns>
        public ApiResponse<TrustedDevicesGetResponse> DevicesGetWithHttpInfo (Guid userId = default(Guid), int top = default(int), long skip = default(long), bool count = default(bool))
        {

            var localVarPath = "/devices";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "*/*"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (userId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "userId", userId)); // query parameter
            if (top != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "$top", top)); // query parameter
            if (skip != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "$skip", skip)); // query parameter
            if (count != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "$count", count)); // query parameter

            // authentication (OAuth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DevicesGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<TrustedDevicesGetResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (TrustedDevicesGetResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(TrustedDevicesGetResponse)));
        }

        /// <summary>
        /// Get the list of trusted devices The API allows to enumerate all the devices of a user. 
        /// </summary>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">Select the objects relative to the user specified by the parameter. If not specified will be used the id of the current authenticated user (optional)</param>
        /// <param name="top">A number of results to return. Applied after **$skip**  (optional)</param>
        /// <param name="skip">An offset into the collection of results (optional)</param>
        /// <param name="count">If true, the server includes the count of all the items in the response  (optional)</param>
        /// <returns>Task of TrustedDevicesGetResponse</returns>
        public async System.Threading.Tasks.Task<TrustedDevicesGetResponse> DevicesGetAsync (Guid userId = default(Guid), int top = default(int), long skip = default(long), bool count = default(bool))
        {
             ApiResponse<TrustedDevicesGetResponse> localVarResponse = await DevicesGetAsyncWithHttpInfo(userId, top, skip, count);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get the list of trusted devices The API allows to enumerate all the devices of a user. 
        /// </summary>
        /// <exception cref="SigningToday.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">Select the objects relative to the user specified by the parameter. If not specified will be used the id of the current authenticated user (optional)</param>
        /// <param name="top">A number of results to return. Applied after **$skip**  (optional)</param>
        /// <param name="skip">An offset into the collection of results (optional)</param>
        /// <param name="count">If true, the server includes the count of all the items in the response  (optional)</param>
        /// <returns>Task of ApiResponse (TrustedDevicesGetResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<TrustedDevicesGetResponse>> DevicesGetAsyncWithHttpInfo (Guid userId = default(Guid), int top = default(int), long skip = default(long), bool count = default(bool))
        {

            var localVarPath = "/devices";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "*/*"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (userId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "userId", userId)); // query parameter
            if (top != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "$top", top)); // query parameter
            if (skip != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "$skip", skip)); // query parameter
            if (count != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "$count", count)); // query parameter

            // authentication (OAuth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DevicesGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<TrustedDevicesGetResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (TrustedDevicesGetResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(TrustedDevicesGetResponse)));
        }

    }
}
